### PR TITLE
fix: add next price negativity check

### LINKED ISSUE #1: HAL-02: Missing NextPrice negativity check
In the `aggregatorMsgServer` the `ReportBalance` function does not ensure that the `NextPrice` is not negative, only if is zero or less/equal than the calculated `answer`.

### PR DESCRIPTION
**Pull request by g-luca**
This PR ensure that the `NextPrice` in the `ReportBalance` is not negative.

Closes #1 .

## Summary by CodeRabbit

- **New Features**
	- Enhanced validation for the next price input in the balance reporting functionality, ensuring that only positive values are accepted.
  
- **Bug Fixes**
	- Improved error handling for scenarios where a negative next price is provided, ensuring invalid inputs are correctly flagged.

- **Tests**
	- Added a new test case to verify the error handling for negative next price values, strengthening the testing suite's coverage.

### CODE REVIEW

File: x/halo/keeper/msg_server_aggregator.go [hunk 1]
```diff
@@ -48,7 +48,7 @@ func (k aggregatorMsgServer) ReportBalance(goCtx context.Context, msg *aggregato
 	}
 	k.SetRound(ctx, id, round)
 
-	if msg.NextPrice.IsZero() || msg.NextPrice.LTE(answer) {
+	if msg.NextPrice.IsNegative() || msg.NextPrice.IsZero() || msg.NextPrice.LTE(answer) {
```
Comment (johnletey) [inline x/halo/keeper/msg_server_aggregator.go:51]: In theory could we simply this to `!msg.NextPrice.IsPositive()`?

That would ensure that it's both not negative and not zero 😄

**Review by johnletey — APPROVED** [review]
Looks great, thanks for working on this! Just one minor cleanup.
